version: "3.2"
services:
  php:
    image: php:7.3-apache
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html
    ports: 
      - '8080:80'
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  frontend:
  backend:
