version: "3.2"
services:
  php:
    build: 
      context: .
      dockerfile: dockerfile
    networks:
      - backend
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html
    ports: 
      - '8080:80'
  mysql:
    container_name: mysql
    image: mysql:5.6.40
    ports: 
      - '3306:3306'
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=dotlog
networks:
  frontend:
  backend:
